language: node_js

node_js:
  - 0.8

install:
  - npm install node-static mocha-phantomjs coveralls jscoverage
  - npm install nico

before_script:
  - git clone git://github.com/aralejs/nico-arale.git _theme
  - node_modules/.bin/nico build --theme _theme -C _theme/nico.js

script:
  - node _theme/server.js _site node_modules/.bin/mocha-phantomjs http://127.0.0.1:8000/tests/runner.html
  - node _theme/server.js _site node_modules/.bin/mocha-phantomjs http://127.0.0.1:8000/tests/runner.html?src

after_script:
  - node_modules/.bin/jscoverage --encoding=utf8 src _site/src-cov
  - node _theme/server.js _site node_modules/.bin/mocha-phantomjs --reporter=json-cov http://127.0.0.1:8000/tests/runner.html?cov  | node _theme/lcov.js | ./node_modules/.bin/coveralls